import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import { readFile, writeFile } from "fs/promises";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository.
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();
  // Strip IE 6-8 script-element polyfills (setimmediate + jszip/asap).
  // Dead code in Electron but flagged by static security scanners.
  let bundle = await readFile("main.js", "utf8");

  // JSZip asap: `"document" in t && "onreadystatechange" in t.document.createElement("script") ? <block> : `
  bundle = bundle.replace(
    /"document" in (\w+) && "onreadystatechange" in \1\.document\.createElement\("script"\) \? function\(\) \{[\s\S]*?\n {12}\} : /,
    ""
  );
  // setimmediate: ` : l && "onreadystatechange" in l.createElement("script") ? (<block>) :`
  bundle = bundle.replace(
    / : (\w+) && "onreadystatechange" in \1\.createElement\("script"\) \? \([\s\S]*?\}\) :/,
    " :"
  );

  await writeFile("main.js", bundle);
  process.exit(0);
} else {
  await context.watch();
}
